

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "20204166/not_backend:latest"
    ports:
      - "5000:5000"        # Expose Flask on host:5000
    volumes:
      - .:/app             # Mount code for development
    depends_on:
      - redis              # Wait for Redis before starting
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"        # Expose Redis on host:6379
