

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KAGGLE_USERNAME: ${KAGGLE_USERNAME}
        KAGGLE_KEY:      ${KAGGLE_KEY}
    image: 20204166/not_backend:latest
 
    ports:
      - "5000:5000"        # Expose Flask on host:5000
    sysctls:
      vm.overcommit_memory: "1"
    depends_on:
      - redis
    command: python run.py
    environment:
      # ─── Flask env & entrypoint ───────────────────────────────
 
      - APP_CONFIG=app.config.Config
      

      # ─── Redis (if you ever use it in your code) ──────────────
      - REDIS_URL=redis://redis:6379

      # ─── Model & tokenizer paths ──────────────────────────────
      #   These override the defaults in config.py
      - MODEL_PATH=app/models/saved_model/summarization_model.keras
      - TOKENIZER_INPUT_PATH=app/models/saved_model/tokenizer_input.json
      - TOKENIZER_TARGET_PATH=app/models/saved_model/tokenizer_target.json
    

      # ─── Sequence-lengths & token indices ─────────────────────
      - MAX_LENGTH_INPUT=50
      - MAX_LENGTH_TARGET=20
      

      # ─── (Optional) other flags from config.py ────────────────
      # - FORCE_REBUILD_MODEL=true
      # - USE_CPU_FOR_TRAINING=false
      # - SECRET_KEY=super-secret-key
      # - LOGGING_LEVEL=DEBUG

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    sysctls:
      vm.overcommit_memory: "1"
