apiVersion: v1
kind: Service
metadata:
  name: ai-notes-backend
  namespace: ai-notes
spec:
  type: LoadBalancer  
  selector:
    app: ai-notes-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http

