apiVersion: v1
kind: Service
metadata:
  name: ai-notes-backend
  namespace: ai-notes
spec:
  type: ClusterIP
  selector:
    app: ai-notes-backend
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP

