# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Run your test suite (e.g., pytest)
          pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build -t ai-notes-backend .
      
      - name: Test Docker Container
        run: |
          docker run --rm -d --name test-backend -p 5000:5000 ai-notes-backend
          sleep 10
          curl -f http://localhost:5000/health
          docker stop test-backend
